### ISSUE TITLE
Functionality: Add dark theme

### ISSUE THREAD

**Issue by AJThePro99** [ss-karthik/calculator#1]
- [x] Add a switch for light theme and dark theme for your website.

- [ ] Also, maybe change the UI a bit, instead of replicating the old school calculator look.
- [ ] Change the layout of the buttons. Keep the Clear and equal buttons on the top, so it takes less effort for the mouse to move.
- [ ] Add an easter egg. *win

**Comment by ss-karthik** [comment]
Added Dark Mode.
The UI is supposed to give a retro calculator look, so no changes.
Rest all nits and thus have been ignored.
